# GitHub Action pour générer une animation du serpent qui mange vos contributions
# À placer dans : .github/workflows/snake.yml

name: Generate Snake

on:
  schedule:
    # S'exécute automatiquement toutes les 24 heures
    - cron: "0 0 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout du repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # Génération des fichiers du serpent
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Fred-69dev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Push vers la branche output
      - name: Push github-contribution-grid-snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
